### ISSUE TITLE
I couldn't find an openeye issue tracker so posting here - Server Crash from OpenEye 1.7.10

### ISSUE THREAD

**Issue by ProsperCraft** [OpenMods/OpenData-protocol#1]
https://gist.github.com/ProsperCraft/6bf95f55377a7ccf8588d14abaf1756e

Description: Exception in server tick loop

java.lang.IllegalArgumentException: Multiple entries with same key: OpenEye=Wrapped{OpenEye} and OpenEye=Wrapped{OpenEye}
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1166)
	at com.google.common.collect.Maps.uniqueIndex(Maps.java:1140)
	at cpw.mods.fml.common.Loader.identifyMods(Loader.java:366)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643)
	at java.lang.Thread.run(Thread.java:748)

**Comment by boq** [comment]
You seem to have multiple OpenEye jars in mod folder.

BTW, OpenEye mod repo is here: https://github.com/OpenMods/OpenData

**Comment by ProsperCraft** [comment]
https://i.gyazo.com/d13d0061052f84158a942ee3df96b559.png

Only one copy, which is now disabled.

**Comment by boq** [comment]
Well, if it's disabled, that how can it cause anything?

**Comment by ProsperCraft** [comment]
Disabled after it crashed the server.

After I disabled the mod, it doesn't show up in the modlist twice on the next crash.
https://gist.github.com/ProsperCraft/43015b2b3545b206fe8869490f096d50

**Comment by boq** [comment]
Ok, can you reproduce that first crash and attach full logs (`logs/fml-server-latest.log`)?
